### ISSUE TITLE
Correct ROS package name

### ISSUE THREAD

**Issue by JimmyDaSilva** [kuka-isir/qpOASES#1]
@ahoarau It's about time we change the package name from `qpOASES` to `qpoases`.

We need to change the name inside the CMakelist.txt and package.xml of the package, but also the dependency name inside all packages we have that depends on it

**Comment by ahoarau** [comment]
I know about the warning, but i'd like to keep consistency between the regular install, and this ros wrapper (i.e. same library name libqpOASES.a, and same cmake variables).

> We need to change the name inside the CMakelist.txt and package.xml of the package, but also the dependency name inside all packages we have that depends on it

That should be sufficient for a nogo :^D

**Comment by JimmyDaSilva** [comment]
I understand that. You can still change the package name to be whatever else that respects the naming convention

**Comment by ahoarau** [comment]
That'll change the dep names for the other packages, so it's preferable to keep it the same as the "standard" qpOASES lib. What you ya think ?

**Comment by vpadois** [comment]
Is that renaming "desire" just a ROS compatibility issue ?

Vincent

**Comment by JimmyDaSilva** [comment]
@vpadois : Yeah just an annoying ROS compatibilty warning popping because package names should not include upper cases... Nothing important here !

@ahoarau : Just saying. The warning pops out at lot, and the fix is quite easy.
The only package I see using this one is mine, cart_opt_ctrl.

**Comment by vpadois** [comment]
I know it's not really a big concern but if it's just a warning then you
may just ignore it. All the software libraries of the world are not going
to change their names just because ROS decided so :)

**Comment by JimmyDaSilva** [comment]
Yep but the library name and the ros package name are too different things and we could follow the two conventions

**Comment by JimmyDaSilva** [comment]
@ahoarau if I only change the ROS package name to `qpoases`, I get the following
```
jimmy@jimmy-laptop:~$ locate libqpOASES
/home/jimmy/catkin_ws/build/qpoases/qpOASES-prefix/src/qpOASES-build/libs/libqpOASES.a
/home/jimmy/catkin_ws/devel/.private/qpoases/lib/libqpOASES.a
/home/jimmy/catkin_ws/devel/lib/libqpOASES.a
```
and 
```
jimmy@jimmy-laptop:~$ locate libqpoases

```
So the lib name is preserved !

I say we change this before all the world starts using our packages ;)

**Comment by ahoarau** [comment]
If you are using the regular `sudo make install` to install `qpOASES` (standard way), then anyway you "need" to include it as a [system dependency](http://docs.ros.org/kinetic/api/catkin/html/howto/format2/system_library_dependencies.html) in your `package.xml` as follow : `<build_depend>qpOASES</build_depend>`.

With this catkin wrapper, this line is preserved as we're using the same package name.

If you change the name of the package, then you'll need to change the dependency to `<build_depend>qpoases</build_depend>`, and that's what we're trying to avoid, so I join @vpadois for keeping it that way.

**Comment by JimmyDaSilva** [comment]
I see what you mean now. So be it then!
